<?php

if ( function_exists( 'acf_add_local_field_group' ) ):
	acf_add_local_field_group(
		array(
			'key'                   => 'group_56448c8e7cd04',
			'title'                 => 'Kirjan tiedot',
			'fields'                => array(
				array(
					'key'               => 'field_5649796b788f0',
					'label'             => 'Alaotsikko',
					'name'              => 'alaotsikko',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_56448c9ae6c4b',
					'label'             => 'Kirjailija',
					'name'              => 'kirjailija',
					'type'              => 'relationship',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'post_type'         => array(
						0 => 'otava_author',
					),
					'taxonomy'          => array(),
					'filters'           => array(
						0 => 'search',
					),
					'elements'          => '',
					'min'               => '',
					'max'               => '',
					'return_format'     => 'object',
				),
				array(
					'key'               => 'field_56448cc0e6c4c',
					'label'             => 'Alkuteos',
					'name'              => 'alkuteos',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_56b88a1957421',
					'label'             => 'Lukija',
					'name'              => 'lukija',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_56448ccae6c4d',
					'label'             => 'ISBN',
					'name'              => 'isbn',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_56448cf1e6c4f',
					'label'             => 'Julkaisuaika',
					'name'              => 'julkaisuaika',
					'type'              => 'date_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'display_format'    => 'd/m/Y',
					'return_format'     => 'Y',
					'first_day'         => 1,
				),
				array(
					'key'               => 'field_566e58695de87',
					'label'             => 'Koko',
					'name'              => 'koko',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => 'mm',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_566e58815de88',
					'label'             => 'Kirjastoluokka',
					'name'              => 'kirjastoluokka',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_564992ae315ba',
					'label'             => 'Kuvitus',
					'name'              => 'kuvitus',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'01' => 'Ei kuvitettu',
						'02' => 'Kuvitettu',
					),
					'default_value'     => array(),
					'allow_null'        => 1,
					'multiple'          => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
					'disabled'          => 0,
					'readonly'          => 0,
					'return_format'     => 'value',
				),
				array(
					'key'               => 'field_5832af301df32',
					'label'             => 'Kirjoittajat',
					'name'              => 'kirjoittajat',
					'type'              => 'repeater',
					'instructions'      => 'Tämä näytetään julkisella puolella kannen ja/tai kirjan nimen yhteydessä. Järjestys tulee Peruslistalta ja sisältää vain kirjailijat ja toimittajat.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'table',
					'button_label'      => 'Lisää kirjoittaja',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5832af861df33',
							'label'             => 'Kirjoittaja',
							'name'              => 'kirjoittaja',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'otava_book',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'side',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_618e506f7d395',
			'title'                 => 'Book Variations',
			'fields'                => array(
				array(
					'key'               => 'field_618e5089b451b',
					'label'             => 'Versions',
					'name'              => 'versions',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'table',
					'button_label'      => '',
					'sub_fields'        => array(
						array(
							'key'               => 'field_618e50aab451c',
							'label'             => 'ISBN',
							'name'              => 'isbn',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_618e50bab451d',
							'label'             => 'Tyyppi',
							'name'              => 'tyyppi',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_61a0fd074a90b',
							'label'             => 'Tuotemuoto',
							'name'              => 'tuotemuoto',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_61a0fd562bb51',
							'label'             => 'Pages',
							'name'              => 'pages',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_61a0fd7be4731',
							'label'             => 'Asu Koodi',
							'name'              => 'asu_code',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_61a0fd8be4732',
							'label'             => 'Asu Text',
							'name'              => 'asu_text',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'otava_book',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	// Kirjailijan tiedot.
	acf_add_local_field_group(
		array(
			'key'                   => 'group_56b88ad222501',
			'title'                 => 'Kirjailijan tiedot',
			'fields'                => array(
				array(
					'key'               => 'field_56b88ad819211',
					'label'             => 'Sukunimi, etunimi',
					'name'              => 'sukunimi_etunimi',
					'type'              => 'text',
					'instructions'      => 'Aakkostus otava.fi ja Osta-painikkeen haku. Huomio, pitää olla muodossa Sukunimi, Etunimi. Huomaa myös erikoistapaukset, jolloin Osta-painikkeen kautta ei löydy kaikki tulokset. Esimerkiksi haulla <strong>"Le Clézio, J. M. G."</strong> palautuu vain osa, mutta pelkällä <strong>"Le Clézio"</strong> tulevat myös kirjoittajan Jean-Marie Gustave Le Clézion kirjoittamat teokset.',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5bbc56f28d396',
					'label'             => 'Nosta etusivulle',
					'name'              => 'nosta_etusivulle',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_5d00f33aecd03',
					'label'             => 'Nemon kirjailija',
					'name'              => 'nemon_kirjailija',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'otava_author',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'side',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

endif;
